name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          version: "20"
      
      - name: Install dependencies
        run: npm ci
  
  lint:
    runs-on: ubuntu-latest
    needs: install-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          version: "20"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run lint
        run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    needs: install-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          version: "20"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run test
        uses: npm test
  
  build:
    runs-on: ubuntu-latest
    needs: ["lint", "test"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          version: "20"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: dist/
